site_name: Anime Royale Wiki
site_url: https://Anime-Royale-Wiki.github.io

theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: red
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - header.autohide

  font:
    text: Inter
    code: Roboto Mono

nav:
  - Home: index.md
  - Units: unit_page.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false

copyright: Copyright &copy; 2026 Anime Royale Wiki

extra_css:
  - assets/css/tailwind.css
  - assets/css/extra.css

extra_javascript:
  - assets/js/unit-filter.js
  - https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js
  - https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
